[package]
name = "abalone-mcts"
version.workspace = true
edition.workspace = true
authors.workspace = true
autobenches = false

[lib]
name = "abalone_mcts"
path = "src/lib.rs"

[dependencies]
abalone-game = { path = "../game" }
rand = { version = "0.8", features = ["small_rng"] }

[[bin]]
name = "mcts-bench"
path = "benches/mcts.rs"

[lints]
workspace = true
