//! D6 (12-element) hex symmetry group.
//!
//! The board is centered at E5 (axial coords `(q, r) = (4, 4)`). In centered
//! coords `(u, v) = (q - 4, r - 4)` the valid hexagon is
//!     `{ (u, v) : |u| <= 4, |v| <= 4, |u - v| <= 4 }`.
//! This set is preserved by the 12-element dihedral group generated by:
//!   * `R(u, v) = (u - v, u)` — 60° CCW rotation cycling
//!     `E -> NE -> NW -> W -> SW -> SE -> E`.
//!   * `F(u, v) = (v, u)` — reflection across the NE-SW diagonal
//!     (swaps `E` and `NW`, swaps `W` and `SE`, fixes `NE` and `SW`).
//!
//! Group elements are indexed `0..12`: `0..6` are `R^k`; `6..12` are `R^k * F`.
//! The two cosets (orientation-preserving rotations vs orientation-reversing
//! reflections) are disjoint by determinant.

use crate::bitboard::BitIter;
use crate::board::Board;
use crate::cell::{in_board, Cell, Dir, Side, N_CELLS};
use crate::moves::Move;

pub const N_SYM: usize = 12;

/// 2x2 integer matrix `(a, b, c, d)` acting on `(u, v)` as
/// `(u', v') = (a*u + b*v, c*u + d*v)`.
type Mat = (i8, i8, i8, i8);

const IDENT: Mat = (1, 0, 0, 1);
const R: Mat = (1, -1, 1, 0);
const F: Mat = (0, 1, 1, 0);

const fn compose(g1: Mat, g2: Mat) -> Mat {
    // Apply g2 first, then g1: (g1 ∘ g2)(x) = g1(g2(x)).
    let (a1, b1, c1, d1) = g1;
    let (a2, b2, c2, d2) = g2;
    (
        a1 * a2 + b1 * c2,
        a1 * b2 + b1 * d2,
        c1 * a2 + d1 * c2,
        c1 * b2 + d1 * d2,
    )
}

const fn build_mats() -> [Mat; N_SYM] {
    let mut out = [IDENT; N_SYM];
    let mut i = 1;
    while i < 6 {
        out[i] = compose(R, out[i - 1]);
        i += 1;
    }
    out[6] = F;
    let mut i = 7;
    while i < 12 {
        out[i] = compose(R, out[i - 1]);
        i += 1;
    }
    out
}

const SYM_MATS: [Mat; N_SYM] = build_mats();

const fn apply_mat_uv(m: Mat, u: i32, v: i32) -> (i32, i32) {
    let (a, b, c, d) = m;
    (a as i32 * u + b as i32 * v, c as i32 * u + d as i32 * v)
}

const fn dir_uv(d: Dir) -> (i32, i32) {
    match d {
        Dir::E => (1, 0),
        Dir::NE => (1, 1),
        Dir::NW => (0, 1),
        Dir::W => (-1, 0),
        Dir::SW => (-1, -1),
        Dir::SE => (0, -1),
    }
}

const fn dir_from_uv(u: i32, v: i32) -> Dir {
    match (u, v) {
        (1, 0) => Dir::E,
        (1, 1) => Dir::NE,
        (0, 1) => Dir::NW,
        (-1, 0) => Dir::W,
        (-1, -1) => Dir::SW,
        (0, -1) => Dir::SE,
        _ => panic!("symmetry mapped a unit direction to a non-direction"),
    }
}

const INVALID_CELL: Cell = 0xFF;

const fn build_cell_table() -> [[Cell; N_CELLS]; N_SYM] {
    let mut out = [[INVALID_CELL; N_CELLS]; N_SYM];
    let mut s = 0;
    while s < N_SYM {
        let m = SYM_MATS[s];
        let mut c: u8 = 0;
        while (c as usize) < N_CELLS {
            let r = c / 9;
            let q = c % 9;
            if in_board(r as u32, q as u32) {
                let u = q as i32 - 4;
                let v = r as i32 - 4;
                let (u2, v2) = apply_mat_uv(m, u, v);
                let q2 = (u2 + 4) as u32;
                let r2 = (v2 + 4) as u32;
                out[s][c as usize] = (r2 * 9 + q2) as Cell;
            }
            c += 1;
        }
        s += 1;
    }
    out
}

const fn build_dir_table() -> [[u8; 6]; N_SYM] {
    let mut out = [[0u8; 6]; N_SYM];
    let mut s = 0;
    while s < N_SYM {
        let m = SYM_MATS[s];
        let mut d = 0;
        while d < 6 {
            let dir = Dir::from_idx(d as u8);
            let (du, dv) = dir_uv(dir);
            let (du2, dv2) = apply_mat_uv(m, du, dv);
            out[s][d] = dir_from_uv(du2, dv2) as u8;
            d += 1;
        }
        s += 1;
    }
    out
}

static SYM_CELL: [[Cell; N_CELLS]; N_SYM] = build_cell_table();
static SYM_DIR: [[u8; 6]; N_SYM] = build_dir_table();

#[derive(Copy, Clone, PartialEq, Eq, Hash, Debug)]
pub struct Sym(u8);

impl Sym {
    pub const IDENTITY: Sym = Sym(0);

    pub const fn new(i: u8) -> Sym {
        debug_assert!((i as usize) < N_SYM);
        Sym(i)
    }

    pub const fn idx(self) -> usize {
        self.0 as usize
    }

    /// Permute a cell. `cell` must be a valid (in-board) cell.
    pub fn cell(self, cell: Cell) -> Cell {
        let out = SYM_CELL[self.0 as usize][cell as usize];
        debug_assert!(out != INVALID_CELL, "Sym::cell on invalid cell");
        out
    }

    pub fn dir(self, d: Dir) -> Dir {
        Dir::from_idx(SYM_DIR[self.0 as usize][d.idx()])
    }

    /// Apply this symmetry to a `Move`. Broadside moves are re-canonicalised
    /// when the transformed `group_dir` falls outside `POSITIVE_DIRS`.
    pub fn apply(self, mv: Move) -> Move {
        match mv {
            Move::Inline { anchor, dir, size } => Move::Inline {
                anchor: self.cell(anchor),
                dir: self.dir(dir),
                size,
            },
            Move::Broadside {
                anchor,
                group_dir,
                move_dir,
                size,
            } => {
                let new_anchor = self.cell(anchor);
                let new_gd = self.dir(group_dir);
                let new_md = self.dir(move_dir);
                if is_positive(new_gd) {
                    Move::Broadside {
                        anchor: new_anchor,
                        group_dir: new_gd,
                        move_dir: new_md,
                        size,
                    }
                } else {
                    let dg = new_gd.shift();
                    let other_end =
                        (new_anchor as i32 + (size as i32 - 1) * dg) as Cell;
                    Move::Broadside {
                        anchor: other_end,
                        group_dir: new_gd.opposite(),
                        move_dir: new_md,
                        size,
                    }
                }
            }
        }
    }
}

const fn is_positive(d: Dir) -> bool {
    matches!(d, Dir::E | Dir::NE | Dir::NW)
}

pub const ALL_SYMS: [Sym; N_SYM] = [
    Sym(0),
    Sym(1),
    Sym(2),
    Sym(3),
    Sym(4),
    Sym(5),
    Sym(6),
    Sym(7),
    Sym(8),
    Sym(9),
    Sym(10),
    Sym(11),
];

/// Apply a symmetry to a `Board`: relabel every marble's cell by `s`. The
/// `pushed_off` counters are invariant (they don't reference cells).
pub fn transform_board(s: Sym, b: &Board) -> Board {
    let mut out = Board::empty();
    out.pushed_off = b.pushed_off;
    for side in [Side::Black, Side::White] {
        for c in BitIter(b.bb(side)) {
            out.set(s.cell(c), Some(side));
        }
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::cell::{parse, ALL_DIRS};
    use crate::moves::legal_moves;
    use std::collections::HashSet;

    #[test]
    fn rotation_has_order_6() {
        let r = Sym::new(1);
        let a1 = parse("A1").unwrap();
        let mut c = a1;
        for _ in 0..6 {
            c = r.cell(c);
        }
        assert_eq!(c, a1);
        let mut c = a1;
        for _ in 0..5 {
            c = r.cell(c);
        }
        assert_ne!(c, a1);
    }

    #[test]
    fn reflection_squared_is_identity() {
        let f = Sym::new(6);
        for c in 0..81u8 {
            let r = c / 9;
            let q = c % 9;
            if !in_board(r as u32, q as u32) {
                continue;
            }
            assert_eq!(f.cell(f.cell(c)), c);
        }
        for d in ALL_DIRS {
            assert_eq!(f.dir(f.dir(d)), d);
        }
    }

    #[test]
    fn identity_fixes_everything() {
        let id = Sym::IDENTITY;
        for c in 0..81u8 {
            let r = c / 9;
            let q = c % 9;
            if !in_board(r as u32, q as u32) {
                continue;
            }
            assert_eq!(id.cell(c), c);
        }
        for d in ALL_DIRS {
            assert_eq!(id.dir(d), d);
        }
    }

    #[test]
    fn r_cycles_corners() {
        let r = Sym::new(1);
        // Hex corners: A1 -> A5 -> E9 -> I9 -> I5 -> E1 -> A1.
        let corners = ["A1", "A5", "E9", "I9", "I5", "E1"];
        for i in 0..6 {
            let from = parse(corners[i]).unwrap();
            let to = parse(corners[(i + 1) % 6]).unwrap();
            assert_eq!(r.cell(from), to, "R({}) should be {}", corners[i], corners[(i + 1) % 6]);
        }
    }

    #[test]
    fn r_cycles_directions() {
        let r = Sym::new(1);
        let cycle = [Dir::E, Dir::NE, Dir::NW, Dir::W, Dir::SW, Dir::SE];
        for i in 0..6 {
            assert_eq!(r.dir(cycle[i]), cycle[(i + 1) % 6]);
        }
    }

    #[test]
    fn f_fixes_ne_sw_axis() {
        let f = Sym::new(6);
        // NE-SW axis runs through E5 (center). Cells on this axis: A1 B2 C3 D4 E5 F6 G7 H8 I9.
        for name in ["A1", "B2", "C3", "D4", "E5", "F6", "G7", "H8", "I9"] {
            let c = parse(name).unwrap();
            assert_eq!(f.cell(c), c, "F should fix {}", name);
        }
        // F swaps E <-> NW, W <-> SE, fixes NE, SW.
        assert_eq!(f.dir(Dir::E), Dir::NW);
        assert_eq!(f.dir(Dir::NW), Dir::E);
        assert_eq!(f.dir(Dir::W), Dir::SE);
        assert_eq!(f.dir(Dir::SE), Dir::W);
        assert_eq!(f.dir(Dir::NE), Dir::NE);
        assert_eq!(f.dir(Dir::SW), Dir::SW);
    }

    #[test]
    fn all_syms_distinct_on_a1() {
        let a1 = parse("A1").unwrap();
        let mut images = HashSet::new();
        for s in ALL_SYMS {
            images.insert(s.cell(a1));
        }
        // A1 is a corner; the 12 group elements collapse to 6 corner images
        // (stabilizer = {identity, reflection across the A1-I9 line}, order 2).
        // So expect exactly 6 distinct images.
        assert_eq!(images.len(), 6);
    }

    #[test]
    fn all_syms_distinct_on_b3() {
        // B3 = (q=2, r=1) is off every reflection axis, so its stabilizer is
        // trivial and the orbit has all 12 elements distinct.
        let b3 = parse("B3").unwrap();
        let mut images = HashSet::new();
        for s in ALL_SYMS {
            images.insert(s.cell(b3));
        }
        assert_eq!(images.len(), N_SYM);
    }

    #[test]
    fn group_closure_via_cell_action() {
        // For each pair (i, j), there's exactly one k such that S_i(S_j(c)) = S_k(c) for all c.
        let probe_a1 = parse("A1").unwrap();
        let probe_b3 = parse("B3").unwrap();
        for i in 0..N_SYM {
            for j in 0..N_SYM {
                let si = Sym::new(i as u8);
                let sj = Sym::new(j as u8);
                let target_a1 = si.cell(sj.cell(probe_a1));
                let target_b3 = si.cell(sj.cell(probe_b3));
                let mut found = false;
                for k in 0..N_SYM {
                    let sk = Sym::new(k as u8);
                    if sk.cell(probe_a1) == target_a1 && sk.cell(probe_b3) == target_b3 {
                        found = true;
                        break;
                    }
                }
                assert!(found, "composition S_{} ∘ S_{} not in the group", i, j);
            }
        }
    }

    #[test]
    fn transform_preserves_marble_count() {
        let b = Board::standard();
        for s in ALL_SYMS {
            let bt = transform_board(s, &b);
            assert_eq!(bt.count(Side::Black), 14);
            assert_eq!(bt.count(Side::White), 14);
        }
    }

    #[test]
    fn transform_round_trips() {
        let b = Board::standard();
        for s in ALL_SYMS {
            let bt = transform_board(s, &b);
            let inverse_exists = ALL_SYMS
                .iter()
                .any(|&s_inv| transform_board(s_inv, &bt) == b);
            assert!(inverse_exists, "no inverse found for sym {}", s.0);
        }
    }

    #[test]
    fn legal_moves_are_equivariant() {
        // The whole point: legal_moves(g·b) = g · legal_moves(b) (as sets).
        for &b in &[Board::standard(), Board::belgian_daisy()] {
            for side in [Side::Black, Side::White] {
                let originals: Vec<Move> = legal_moves(&b, side).into_iter().collect();
                for s in ALL_SYMS {
                    let bt = transform_board(s, &b);
                    let actual: HashSet<Move> = legal_moves(&bt, side).into_iter().collect();
                    let expected: HashSet<Move> =
                        originals.iter().map(|&m| s.apply(m)).collect();
                    assert_eq!(
                        actual, expected,
                        "sym {} not equivariant on {:?} side",
                        s.0, side
                    );
                }
            }
        }
    }

    #[test]
    fn apply_to_inline_uses_anchor_and_dir() {
        // Inline at A1 going E (size 2) with R (60°) should land at A5 going NE.
        // A1 -> A5 (corner cycle), E -> NE.
        let r = Sym::new(1);
        let mv = Move::Inline {
            anchor: parse("A1").unwrap(),
            dir: Dir::E,
            size: 2,
        };
        let mvt = r.apply(mv);
        assert_eq!(
            mvt,
            Move::Inline {
                anchor: parse("A5").unwrap(),
                dir: Dir::NE,
                size: 2,
            }
        );
    }

    #[test]
    fn apply_to_broadside_renormalises() {
        // Take a broadside move whose group_dir transforms to a NEGATIVE_DIR.
        // E.g. group_dir = E under R^3 (180°) becomes W. Re-anchor at the other end.
        // Group cells = {C3, C4} (anchor C3, group_dir E, size 2).
        let mv = Move::Broadside {
            anchor: parse("C3").unwrap(),
            group_dir: Dir::E,
            move_dir: Dir::NE,
            size: 2,
        };
        let r3 = Sym::new(3);
        let mvt = r3.apply(mv);
        // R^3 = 180° rotation: (u, v) -> (-u, -v). C3 = (q=2, r=2) = (u=-2, v=-2) -> (2, 2) = (q=6, r=6) = G7.
        // C4 = (q=3, r=2) = (u=-1, v=-2) -> (1, 2) = (q=5, r=6) = G6.
        // Cell pair {G6, G7}. Group_dir E -> W under R^3.
        // Re-anchored: anchor must be the cell from which we step W to reach the rest.
        // Stepping W from G7 (q=6) gives G6 (q=5). So anchor = G7, group_dir = E (the opposite of W).
        // But we said group_dir transforms E -> W; we re-canonicalise to E. After reanchor, anchor = G7.
        // Wait: original cells are anchor + i*dg for i=0..size-1. After transform, new_anchor = G7 (image of C3).
        // dg_new = W (shift -1). other_end = G7 + 1*(-1) = G6. So we re-anchor at G6, group_dir = E (W.opposite()).
        // Cells from new encoding: G6, G6+E = G7. ✓ Same set.
        // move_dir NE -> SW under R^3.
        assert_eq!(
            mvt,
            Move::Broadside {
                anchor: parse("G6").unwrap(),
                group_dir: Dir::E,
                move_dir: Dir::SW,
                size: 2,
            }
        );
    }

}
